### ISSUE TITLE
should chunkupload be using tempdir?

### ISSUE THREAD

**Issue by danmarsden** [Opencast-Moodle/moodle-local_chunkupload#13]
https://github.com/learnweb/moodle-local_chunkupload/blob/master/classes/chunkupload_form_element.php#L263

I'm tempted to suggest changing that to drop it into tempdir rather than the root of dataroot.

(not a blocker - just a suggestion - feel free to close as won't fix.)

**Comment by justusdieckmann** [comment]
In my opinion, since all files already get deleted by our cleanup task, I'd rather not do that for now, just to definitely eliminate the possibility that uploadfiles are deleted because of the tempdir cleanup before they are supposed to (according to the `stage0/1/2duration`-configs).

Greetings,
Justus

**Comment by danmarsden** [comment]
do you mind changing that from "chunkupload" to "local_chunkupload"  - it just makes it a bit clearer what is responsible for storing files in that directory - just thinking of the poor sysadmin that has to decide if this directory should be included in server backups.
